stages:
- stage: Build
  jobs:
  - job: BuildJob
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: echo "Building the application..."
      displayName: 'Build Stage'

# Эти три стадии стартуют одновременно после Build
- stage: Deploy
  dependsOn: Build
  condition: false    # <-- Пропустить Deploy
  jobs:
  - job: DeployJob
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: echo "Deploying the application..."
      displayName: 'Deploy Stage'

- stage: Deploy1
  dependsOn: Build
  jobs:
  - job: DeployJob
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: echo "Deploying the application..."
      displayName: 'Deploy1 Stage'

- stage: Deploy2
  dependsOn: Build
  condition: false    # <-- Пропустить Deploy2
  jobs:
  - job: DeployJob
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: echo "Deploying the application..."
      displayName: 'Deploy2 Stage'
