trigger:
- main

stages:
- stage: Stage1
  jobs:
  - job: Job1
    steps:
    - script: echo "Step 1 in Stage 1"
    - script: echo "Step 2 in Stage 1"
    - script: echo "Step 3 in Stage 1"

- stage: Stage2
  jobs:
  - job: Job1
    steps:
    - script: echo "Step 1 in Stage 2"
    - script: echo "Step 2 in Stage 2"
    - script: echo "Step 3 in Stage 2"
