# azure-pipelines.yml
 
trigger:

- main  # or 'master', depending on your default branch
 
pool:

  vmImage: 'ubuntu-latest'
 
steps:

- checkout: self
 
- script: echo "Hello from Azure DevOps Pipeline!"

  displayName: 'Run a one-line script'

 