trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Preparation
  displayName: 'Preparation'
  jobs:
  - job: Job1
    steps:
    - script: echo "Preparation stage completed successfully"
      displayName: 'Prepare Environment'

- stage: Build
  displayName: 'Build'
  jobs:
  - job: Job1
    steps:
    - script: exit 1
      displayName: 'Intentional Build Failure'

- stage: PostProcess
  displayName: 'Post-Process'
  jobs:
  - job: Job1
    steps:
    - script: echo "Hello"
      displayName: 'Print Hello'
